# NumPy

In [1]:
import numpy as np

In [3]:
# numpy liste
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# numpy matrix
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# numpy range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# numpy zeros: sıfırlar matrisi
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
# numpy ones: birler matrisi
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# numpy eye: diagonal birler matrisi
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# numpy linspace: x, y aralığında n eşit aralıklı sayı üretme
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
# numpy rand: 0-1 aralığın rastgele sayı üretme
np.random.rand(5,5)

array([[0.79419531, 0.44357215, 0.82635038, 0.22051851, 0.31775253],
       [0.34770665, 0.77421798, 0.2786896 , 0.7877895 , 0.0361998 ],
       [0.46076305, 0.0340604 , 0.71437399, 0.81743758, 0.12566061],
       [0.58035482, 0.7896486 , 0.21967388, 0.15189798, 0.75289738],
       [0.40333322, 0.10402665, 0.79497302, 0.97025695, 0.66515234]])

In [16]:
# numpy randn: standart normal dağılımdan sayı üretme
np.random.randn(5,5)

array([[-0.85927248,  0.3778851 ,  0.75723009, -0.06866041, -0.30636752],
       [-0.90040687,  2.05628542,  0.09281949, -1.789175  , -1.26157321],
       [-2.27528898,  0.84321664,  0.04439257, -2.31930241,  1.12153991],
       [ 0.78197045,  1.58351368, -0.74126374, -1.40927253, -0.3632658 ],
       [-0.32058519, -0.17454947, -0.59806522, -0.2856734 , -1.79115164]])

In [18]:
# numpy randint: x, y aralığında n tane sayı üretme
np.random.randint(1,100,10)

array([77, 74, 88, 50, 93, 57, 64, 39, 52, 81])

In [19]:
# numpy reshape: yeniden boyutlandırma
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
# numpy max,min,argmax,argmin: max-min bulma, argmax-argmin ile değerlerin indexini alma
arr = np.random.randint(0,50,10)
arr

array([31, 12,  6, 27,  1, 13, 17, 44, 46,  5])

In [22]:
arr.min()

1

In [23]:
arr.argmin()

4

In [24]:
arr.max()

46

In [25]:
arr.argmax()

8

In [27]:
# numpy shape: objenin boyutlarını alma
arr.reshape(2,5).shape

(2, 5)

In [28]:
# numpy dtype: objenin data tipini öğrenme
arr.dtype

dtype('int32')

**NumPy Indexing**

In [38]:
# numpy dizilerde farklı şekillerde index verme
arr = np.random.randint(0,50,10)
print(arr)
print(arr[8])
print(arr[1:3])
print(arr[0:5])
print(arr[:4])
print(arr[2:])

[15 43 26 29 17 17 18 13 43 33]
43
[43 26]
[15 43 26 29 17]
[15 43 26 29]
[26 29 17 17 18 13 43 33]


In [33]:
# belli bir aralığa değer verme
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  23,  26,  33,  10,  35])

In [34]:
# numpy referans objelidir.
# Başka bir objeye set edildiğinde, obje üzerinde yapılan işlemler
# referans aldığı obje üzerinde değişikliğe neden olur.
arr = np.random.randint(0,50,10)
print(arr)
slice_of_arr = arr[0:6]
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[48 16 18 21 30 11  6 23 29 11]
[48 16 18 21 30 11]
[99 99 99 99 99 99]
[99 99 99 99 99 99  6 23 29 11]


In [35]:
# referans alınan objeyi etkilememek için copy kullanılır.
arr = np.random.randint(0,50,10)
print(arr)
slice_of_arr = arr.copy()
print(slice_of_arr)
slice_of_arr[:] = 99
print(slice_of_arr)
print(arr)

[15 39 34 40 12 29 46 31 41 39]
[15 39 34 40 12 29 46 31 41 39]
[99 99 99 99 99 99 99 99 99 99]
[15 39 34 40 12 29 46 31 41 39]


**NumPy Indexing on matrixs**

In [44]:
# numpy matrixlerde farklı şekillerde index verme
arr = np.random.randint(0,50,15).reshape(3,5)
print(arr)

# bir satır alma
print(arr[1])

# bir değer alma
print(arr[1][2])
print(arr[0,1])

# belli bir aralık alma
print(arr[0:2,0:2])
print(arr[1:,:3])

[[37 13 33 13 35]
 [22 36 36 28 15]
 [30 15  5 34  9]]
[22 36 36 28 15]
36
13
[[37 13]
 [22 36]]
[[22 36 36]
 [30 15  5]]


**NumPy Conditional Selection**

In [49]:
# koşula göre elemanları alma
arr = np.random.randint(0,50,10)
print(arr)
print(arr > 30)
print(arr[arr > 30])

[30 47 29 24 22  4  3 19 27 12]
[False  True False False False False False False False False]
[47]


**NumPy Arithmetic and Universal Array Functions**

In [51]:
arr = np.random.randint(0,50,10)
print(arr)
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr / arr)
print(arr ** 3)

[23 49 33 15  3 28 18 21 47 45]
[46 98 66 30  6 56 36 42 94 90]
[0 0 0 0 0 0 0 0 0 0]
[ 529 2401 1089  225    9  784  324  441 2209 2025]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 12167 117649  35937   3375     27  21952   5832   9261 103823  91125]


In [53]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.max(arr)) # arr.max()
print(np.sin(arr))
print(np.log(arr))

[4.79583152 7.         5.74456265 3.87298335 1.73205081 5.29150262
 4.24264069 4.58257569 6.8556546  6.70820393]
[9.74480345e+09 1.90734657e+21 2.14643580e+14 3.26901737e+06
 2.00855369e+01 1.44625706e+12 6.56599691e+07 1.31881573e+09
 2.58131289e+20 3.49342711e+19]
49
[-0.8462204  -0.95375265  0.99991186  0.65028784  0.14112001  0.27090579
 -0.75098725  0.83665564  0.12357312  0.85090352]
[3.13549422 3.8918203  3.49650756 2.7080502  1.09861229 3.33220451
 2.89037176 3.04452244 3.8501476  3.80666249]


# Pandas

In [54]:
import pandas as pd

**Series: Diziler**

In [55]:
labels = ['a','b','c']
my_list = [10,20,30]
print(pd.Series(data=my_list))
print(pd.Series(data=my_list,index=labels))
print(pd.Series(my_list,labels))

0    10
1    20
2    30
dtype: int64
a    10
b    20
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64


In [56]:
arr = np.array([10,20,30])
print(pd.Series(arr))
print(pd.Series(arr,labels))

0    10
1    20
2    30
dtype: int32
a    10
b    20
c    30
dtype: int32


In [57]:
d = {'a':10,'b':20,'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [59]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
print(ser1)
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])
print(ser2)
print(ser1['USA'])
print(ser1 + ser2)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64
USA        1
Germany    2
Italy      5
Japan      4
dtype: int64
1
Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64


**DataFrames: Matrixler**

In [62]:
from numpy.random import randn
np.random.seed(101) # random üretirken aynı sayıları üretmeyi sağlar
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

**Selection and Indexing**

In [63]:
print(df['W'])
print(df[['W','Z']])
print(df.W) # tavsiye edilmez
type(df['W']) # DataFrame, Series dizilerinden oluşan bir matrixdir.

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64
          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509
A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64


pandas.core.series.Series

In [69]:
# yeni kolon yaratma
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [70]:
# kolon silme
print(df.drop('new',axis=1)) # anlık olarak o kolonu göstermez. Bu işlem asıl objeyi etkilemiyor
print(df)
print(df.drop('new',axis=1,inplace=True))
print(df)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762
None
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509


In [71]:
# Selecting Rows
# loc (colon adı) veya iloc (index location-index no)
print(df.loc['A'])
print(df.iloc[2])

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64
W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64


In [76]:
# Selecting subset of rows and columns
print(df.loc['B','Y'])
print(df.loc[['A','B'],['W','Y']])
print(df.iloc[2,3])
print(df.iloc[[0,2],[1,2]])
print(df.iloc[0:2,1:3])

-0.8480769834036315
          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
-0.5890005332865824
          X         Y
A  0.628133  0.907969
C  0.740122  0.528813
          X         Y
A  0.628133  0.907969
B -0.319318 -0.848077


**Conditional Selection**

In [85]:
print(df)
print(df > 0)
print(df[df > 0])
print(df[df['W']>0])
print(df[df['W']>0]['Y'])
print(df[df['W']>0][['Y','X']])
print(df[(df['W']>0) & (df['Y'] > 1)])

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509
          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64
          Y         X
A  0

In [90]:
print(df)
print(df.reset_index())
df['States'] = 'CA NY WY OR CO'.split()
print(df)
print(df.set_index('States')) # anlık gösterir, objeye uygulamaz
print(df)
print(df.set_index('States',inplace=True))
print(df)

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO
  index         W         X         Y         Z States
0     A  2.706850  0.628133  0.907969  0.503826     CA
1     B  0.651118 -0.319318 -0.848077  0.605965     NY
2     C -2.018168  0.740122  0.528813 -0.589001     WY
3     D  0.188695 -0.758872 -0.933237  0.955057     OR
4     E  0.190794  1.978757  2.605967  0.683509     CO
          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO
               W         X         Y         Z
States                             

**Multi-Index and Index Hierarchy**

In [91]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [93]:
print(df.loc['G1'])
print(df.loc['G1'].loc[1])

          A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528
A    0.302665
B    1.693723
Name: 1, dtype: float64


In [95]:
df.index.names

FrozenList([None, None])

In [96]:
df.index.names = ['Group','Num']
df

A         B
Group Num                    
G1    1    0.302665  1.693723
      2   -1.706086 -1.159119
      3   -0.134841  0.390528
G2    1    0.166905  0.184502
      2    0.807706  0.072960
      3    0.638787  0.329646

In [97]:
df.xs('G1')

A         B
Num                    
1    0.302665  1.693723
2   -1.706086 -1.159119
3   -0.134841  0.390528

In [98]:
df.xs(['G1',1])

A    0.302665
B    1.693723
Name: (G1, 1), dtype: float64

In [99]:
df.xs(1,level='Num')

A         B
Group                    
G1     0.302665  1.693723
G2     0.166905  0.184502

**Missing Data**

In [100]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [105]:
print(df.dropna()) # axis varsayılan 0 olarak yani satır bazlı bütün değerleri olan satırları getirir.
print(df.dropna(axis=1)) # axis 1 yani kolon bazlı bütün değerleri olan kolonları getirir.
print(df.dropna(thresh=2)) # min 2 değeri olan alanları getirir.
print(df.fillna(value='FILL VALUE')) # boş alanları verilen değer ile doldurur.
print(df['A'].fillna(value=df['A'].mean())) # boş değerleri ortalama ile doldurur.

     A    B  C
0  1.0  5.0  1
   C
0  1
1  2
2  3
     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
            A           B  C
0           1           5  1
1           2  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3
0    1.0
1    2.0
2    1.5
Name: A, dtype: float64


**Groupby**

In [106]:
data = {'Company':['GOOG','GOOG','MSFT','MSFT','FB','FB'],
       'Person':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
       'Sales':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [109]:
print(df.groupby('Company').mean())
print(df.groupby('Company').std())
print(df.groupby('Company').min())
print(df.groupby('Company').max())
print(df.groupby('Company').count())
print(df.groupby('Company').describe())
print(df.groupby('Company').describe().transpose())

         Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0
              Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065
          Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124
          Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340
         Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2
        Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0
Company              FB        GOOG        MSFT
Sa

**Merging, Joining, and Concatenating**

In [111]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                        index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                         index=[4, 5, 6, 7]) 
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                        'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                        index=[8, 9, 10, 11])

In [112]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [113]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [116]:
left = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
   
right = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],
                          'C': ['C0', 'C1', 'C2', 'C3'],
                          'D': ['D0', 'D1', 'D2', 'D3']})
pd.merge(left,right,how='inner',on='key')

A   B key   C   D
0  A0  B0  K0  C0  D0
1  A1  B1  K1  C1  D1
2  A2  B2  K2  C2  D2
3  A3  B3  K3  C3  D3

In [117]:
left = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                        'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3']})
    
right = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                               'key2': ['K0', 'K0', 'K0', 'K0'],
                                  'C': ['C0', 'C1', 'C2', 'C3'],
                                  'D': ['D0', 'D1', 'D2', 'D3']})

In [118]:
pd.merge(left, right, on=['key1', 'key2'])

A   B key1 key2   C   D
0  A0  B0   K0   K0  C0  D0
1  A2  B2   K1   K0  C1  D1
2  A2  B2   K1   K0  C2  D2

In [119]:
pd.merge(left, right, how='outer', on=['key1', 'key2'])

A    B key1 key2    C    D
0   A0   B0   K0   K0   C0   D0
1   A1   B1   K0   K1  NaN  NaN
2   A2   B2   K1   K0   C1   D1
3   A2   B2   K1   K0   C2   D2
4   A3   B3   K2   K1  NaN  NaN
5  NaN  NaN   K2   K0   C3   D3

In [120]:
pd.merge(left, right, how='right', on=['key1', 'key2'])

A    B key1 key2   C   D
0   A0   B0   K0   K0  C0  D0
1   A2   B2   K1   K0  C1  D1
2   A2   B2   K1   K0  C2  D2
3  NaN  NaN   K2   K0  C3  D3

In [121]:
pd.merge(left, right, how='left', on=['key1', 'key2'])

A   B key1 key2    C    D
0  A0  B0   K0   K0   C0   D0
1  A1  B1   K0   K1  NaN  NaN
2  A2  B2   K1   K0   C1   D1
3  A2  B2   K1   K0   C2   D2
4  A3  B3   K2   K1  NaN  NaN

In [122]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                     'B': ['B0', 'B1', 'B2']},
                      index=['K0', 'K1', 'K2']) 

right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])

In [123]:
left.join(right)

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [124]:
left.join(right, how='outer')

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

**Operations**

In [125]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [129]:
# Info on Unique Values
print(df['col2'].unique()) # unique: set data tipi gibi kümeleme yapar yani tekrar edenleri tekrar yazmaz.
print(df['col2'].nunique()) # nunique: unique elemanların sayısını gösterir.
print(df['col2'].value_counts()) # value_counts: elemanların sayısı gösterir.

[444 555 666]
3
444    2
555    1
666    1
Name: col2, dtype: int64


In [130]:
# Selecting Data
df[(df['col1']>2) & (df['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [133]:
# Applying Functions
def times2(x):
    return x*2
print(df['col1'].apply(times2))
print(df['col3'].apply(len))
print(df['col1'].sum())

0    2
1    4
2    6
3    8
Name: col1, dtype: int64
0    3
1    3
2    3
3    3
Name: col3, dtype: int64
10


In [135]:
# Permanently Removing a Column
# del df['col1']

In [136]:
# Get column and index names
print(df.columns)
print(df.index)

Index(['col1', 'col2', 'col3'], dtype='object')
RangeIndex(start=0, stop=4, step=1)


In [138]:
# Find Null Values or Check for Null Values
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [139]:
# Drop rows with NaN Values
df.dropna()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [140]:
# Filling in NaN values with something else
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [141]:
df.fillna('FILL')

col1  col2 col3
0     1  FILL  abc
1     2   555  def
2     3   666  ghi
3  FILL   444  xyz

In [142]:
# Pivot Table
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}
df = pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [143]:
df.pivot_table(values='D',index=['A', 'B'],columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

**Data Input and Output**

In [146]:
# CSV File
df = pd.read_csv('03- General Pandas\example')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [148]:
df.to_csv('03- General Pandas\example2',index=False)

In [151]:
# Excel File
pd.read_excel('03- General Pandas\Excel_Sample.xlsx',sheet_name='Sheet1')

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [152]:
df.to_excel('03- General Pandas\Excel_Sample2.xlsx',sheet_name='Sheet1')

In [156]:
# HTML
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')
df[0]

Bank Name                City  \
0                  Washington Federal Bank for Savings             Chicago   
1      The Farmers and Merchants State Bank of Argonia             Argonia   
2                                  Fayette County Bank          Saint Elmo   
3    Guaranty Bank, (d/b/a BestBank in Georgia & Mi...           Milwaukee   
4                                       First NBC Bank         New Orleans   
5                                        Proficio Bank  Cottonwood Heights   
6                        Seaway Bank and Trust Company             Chicago   
7                               Harvest Community Bank          Pennsville   
8                                          Allied Bank            Mulberry   
9                         The Woodbury Banking Company            Woodbury   
10                              First CornerStone Bank     King of Prussia   
11                                  Trust Company Bank             Memphis   
12                          North Milwaukee State Bank           Milwaukee   
13                              Hometown National Bank            Longview   
14                                 The Bank of Georgia      Peachtree City   
15                                        Premier Bank              Denver   
16                                      Edgebrook Bank             Chicago   
17                              Doral Bank  En Espanol            San Juan   
18                   Capitol City Bank & Trust Company             Atlanta   
19                             Highland Community Bank             Chicago   
20                    First National Bank of Crestview           Crestview   
21                                  Northern Star Bank             Mankato   
22              Frontier Bank, FSB D/B/A El Paseo Bank         Palm Desert   
23               The National Republic Bank of Chicago             Chicago   
24                                      NBRS Financial          Rising Sun   
25                               GreenChoice Bank, fsb             Chicago   
26                            Eastside Commercial Bank             Conyers   
27                              The Freedom State Bank             Freedom   
28                                         Valley Bank     Fort Lauderdale   
29                                         Valley Bank              Moline   
..                                                 ...                 ...   
525                                  ANB Financial, NA         Bentonville   
526                                          Hume Bank                Hume   
527                             Douglass National Bank         Kansas City   
528                                  Miami Valley Bank            Lakeview   
529                                            NetBank          Alpharetta   
530                          Metropolitan Savings Bank          Pittsburgh   
531                                    Bank of Ephraim             Ephraim   
532                                      Reliance Bank        White Plains   
533              Guaranty National Bank of Tallahassee         Tallahassee   
534                                Dollar Savings Bank              Newark   
535                               Pulaski Savings Bank        Philadelphia   
536              First National Bank of Blanchardville      Blanchardville   
537                              Southern Pacific Bank            Torrance   
538                        Farmers Bank of Cheneyville         Cheneyville   
539                                      Bank of Alamo               Alamo   
540             AmTrade International Bank  En Espanol             Atlanta   
541                     Universal Federal Savings Bank             Chicago   
542                       Connecticut Bank of Commerce            Stamford   
543                                   New Century Bank     Shelby Township   
544                              Net 1st National Bank          Boc