In [1]:
import numpy as np

In [2]:
# numpy liste
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# numpy matrix
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# numpy range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# numpy zeros: sıfırlar matrisi
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
# numpy ones: birler matrisi
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
# numpy eye: diagonal birler matrisi
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# numpy linspace: x, y aralığında n eşit aralıklı sayı üretme
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [9]:
# numpy rand: 0-1 aralığın rastgele sayı üretme
np.random.rand(5,5)

array([[0.84994837, 0.53966344, 0.94623207, 0.33698746, 0.34953623],
       [0.76611069, 0.57721735, 0.40472879, 0.72059348, 0.81083687],
       [0.01190898, 0.92459584, 0.79508134, 0.60145216, 0.43628196],
       [0.29756763, 0.2002861 , 0.62571807, 0.23990745, 0.10439084],
       [0.92091605, 0.29872725, 0.46304154, 0.05672701, 0.6304284 ]])

In [10]:
# numpy randn: standart normal dağılımdan sayı üretme
np.random.randn(5,5)

array([[-7.84992318e-01,  7.40959659e-01,  1.24986282e-01,
        -4.48742254e-01,  5.57576580e-01],
       [ 2.58362216e-01,  1.91966649e+00, -1.61019288e+00,
        -1.85419296e-03,  3.70630514e-01],
       [-8.32896204e-01, -1.96038236e-01, -5.03978943e-01,
        -2.92248810e-01, -6.32633592e-02],
       [ 1.46745411e+00, -1.15870808e+00, -7.36861191e-01,
         2.78522060e+00, -1.77623407e+00],
       [-1.45129550e+00,  4.67410693e-01,  7.43749083e-01,
         2.42807726e-01, -4.98664728e-01]])

In [11]:
# numpy randint: x, y aralığında n tane sayı üretme
np.random.randint(1,100,10)

array([98, 73, 70, 64, 80, 92, 98, 14, 59, 61])

In [12]:
# numpy reshape: yeniden boyutlandırma
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr = np.random.randint(0,50,10)
arr

array([10, 15, 23,  3, 37,  6, 11, 35, 48, 39])

In [19]:
# numpy max: en büyük elemanı bulma
arr.max()

48

In [22]:
# numpy argmax: en büyük elemanın indexini gösterir
arr.argmax()

8

In [23]:
# numpy min: en küçük elemanı bulma
arr.min()

3

In [25]:
# numpy argmin: en küçük elemanın indexini gösterir
arr.argmin()

3

In [26]:
# numpy shape: objenin boyutlarını alma
arr.reshape(2,5).shape

(2, 5)

In [27]:
# numpy dtype: objenin data tipini öğrenme
arr.dtype

dtype('int32')

# NumPy Indexing

In [34]:
# numpy dizilerde farklı şekillerde index verme
arr = np.random.randint(0,50,10)
arr

array([23, 35,  0, 34, 25, 32, 40, 18, 24, 24])

In [35]:
arr[8]

24

In [36]:
arr[1:3]

array([35,  0])

In [37]:
arr[0:5]

array([23, 35,  0, 34, 25])

In [38]:
arr[:4]

array([23, 35,  0, 34])

In [39]:
arr[2:]

array([ 0, 34, 25, 32, 40, 18, 24, 24])

In [29]:
# belli bir aralığa değer verme
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  14,  19,  34,  14,  44])

In [41]:
# numpy referans objelidir.
# Başka bir objeye set edildiğinde, obje üzerinde yapılan işlemler
# referans aldığı obje üzerinde değişikliğe neden olur.
arr = np.random.randint(0,50,10)
arr

array([24, 36,  0, 27, 27, 23, 25, 41,  6, 15])

In [42]:
slice_of_arr = arr[0:6]
slice_of_arr

array([24, 36,  0, 27, 27, 23])

In [43]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [44]:
arr

array([99, 99, 99, 99, 99, 99, 25, 41,  6, 15])

In [46]:
# referans alınan objeyi etkilememek için copy kullanılır.
arr = np.random.randint(0,50,10)
arr

array([ 5,  1, 44, 17, 12, 37, 18, 13, 29,  8])

In [47]:
slice_of_arr = arr.copy()
slice_of_arr

array([ 5,  1, 44, 17, 12, 37, 18, 13, 29,  8])

In [48]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [49]:
arr

array([ 5,  1, 44, 17, 12, 37, 18, 13, 29,  8])

# NumPy Indexing on matrixs

In [50]:
# numpy matrixlerde farklı şekillerde index verme
arr = np.random.randint(0,50,15).reshape(3,5)
arr

array([[ 3, 11,  3, 32, 27],
       [24,  6, 36, 49,  3],
       [ 0, 28, 12,  6, 40]])

In [56]:
# bir satır alma
arr[1]

array([24,  6, 36, 49,  3])

In [52]:
# bir değer alma
arr[1][2]

36

In [53]:
arr[0,1]

11

In [54]:
# belli bir aralık alma
arr[0:2,0:2]

array([[ 3, 11],
       [24,  6]])

In [55]:
arr[1:,:3]

array([[24,  6, 36],
       [ 0, 28, 12]])

In [58]:
arr[1,:]

array([24,  6, 36, 49,  3])

# NumPy Conditional Selection

In [59]:
# koşula göre elemanları alma
arr = np.random.randint(0,50,10)
arr

array([13,  6,  0, 15, 29, 38, 25, 26,  1, 43])

In [60]:
arr > 30

array([False, False, False, False, False,  True, False, False, False,
        True])

In [61]:
arr[arr > 30]

array([38, 43])

# NumPy Arithmetic

In [62]:
arr = np.random.randint(0,50,10)
arr

array([47, 48, 14, 27,  5, 18, 12, 29, 37, 45])

In [64]:
arr + arr

array([94, 96, 28, 54, 10, 36, 24, 58, 74, 90])

In [65]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
arr * arr

array([2209, 2304,  196,  729,   25,  324,  144,  841, 1369, 2025])

In [67]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [68]:
arr ** 3

array([103823, 110592,   2744,  19683,    125,   5832,   1728,  24389,
        50653,  91125], dtype=int32)

# NumPy Universal Array Functions

In [69]:
np.sqrt(arr)

array([6.8556546 , 6.92820323, 3.74165739, 5.19615242, 2.23606798,
       4.24264069, 3.46410162, 5.38516481, 6.08276253, 6.70820393])

In [70]:
np.exp(arr)

array([2.58131289e+20, 7.01673591e+20, 1.20260428e+06, 5.32048241e+11,
       1.48413159e+02, 6.56599691e+07, 1.62754791e+05, 3.93133430e+12,
       1.17191424e+16, 3.49342711e+19])

In [71]:
np.max(arr) # arr.max()

48

In [72]:
np.sin(arr)

array([ 0.12357312, -0.76825466,  0.99060736,  0.95637593, -0.95892427,
       -0.75098725, -0.53657292, -0.66363388, -0.64353813,  0.85090352])

In [73]:
np.log(arr)

array([3.8501476 , 3.87120101, 2.63905733, 3.29583687, 1.60943791,
       2.89037176, 2.48490665, 3.36729583, 3.61091791, 3.80666249])